### ISSUE TITLE
I want to play 大灾变

### ISSUE THREAD

**Issue by Newuser20220124** [tydaytygx/CSGO-plugins-localization#3]
Is there a suitable plug-in available please? Thanks~

**Comment by tydaytygx** [comment]
> 
[zombie riot](https://forums.alliedmods.net/showthread.php?t=335402)
[zombie escape](https://forums.alliedmods.net/showthread.php?t=326056)
Thanks for your suggestion!
Yes, the most similar modes in csgo are these two 
>zombie riot  

>zombie escape (running with zombie)
--------------
感谢你的提议！
当然有，最相似的两个模式为
>zombie riot 僵尸暴动 

>zombie escape 僵尸逃跑 (更偏向于跑)
